#include <iostream.h>
#include <conio.h>

 main () {

   cout<<"1 && 1 = "<<(1 && 1)<<end1;
   cout<<"1 && 0 = "<<(1 && 0)<<end1;
   cout<<"0 && 0 = "<<(0 && 0)<<end1;
   cout<<"0 && 1 = "<<(0 && 1)<<end1;

   cout<<"1 || 1 = "<<(1 || 1)<<end1;
   cout<<"1 || 0 = "<<(1 || 0)<<end1;
   cout<<"0 || 0 = "<<(0 || 0)<<end1;

   cout<<"!1 = "<<!1<<end1;
   cout<<"!0 = "<<!0<<end1;
   getc ();}
